/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const EventCreateRequest = IDL.Record({
  'date' : Time,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const CreateOrderRequest = IDL.Record({
  'customerName' : IDL.Text,
  'orderDate' : Time,
  'fulfillDate' : Time,
  'numberOfDvd' : IDL.Nat,
  'numberOfPrints' : IDL.Nat,
});
export const SpecialMomentCreateRequest = IDL.Record({
  'date' : Time,
  'name' : IDL.Text,
});
export const SortedOrder = IDL.Variant({
  'newestFirst' : IDL.Null,
  'oldestFirst' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const EventImage = IDL.Record({
  'id' : IDL.Text,
  'blob' : ExternalBlob,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'uploadTime' : Time,
});
export const EventDTO = IDL.Record({
  'id' : IDL.Nat,
  'date' : Time,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'passwordProtected' : IDL.Bool,
  'images' : IDL.Vec(EventImage),
});
export const OrderStatus = IDL.Variant({
  'Cancelled' : IDL.Null,
  'Fulfilled' : IDL.Null,
  'Pending' : IDL.Null,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'status' : OrderStatus,
  'orderDate' : Time,
  'fulfillDate' : Time,
  'numberOfDvd' : IDL.Nat,
  'numberOfPrints' : IDL.Nat,
});
export const Photo = IDL.Record({
  'id' : IDL.Text,
  'likeCount' : IDL.Nat,
  'blob' : ExternalBlob,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'uploadTime' : Time,
});
export const UserShortlistDTO = IDL.Record({
  'eventId' : IDL.Nat,
  'user' : IDL.Principal,
  'images' : IDL.Vec(IDL.Text),
});
export const SpecialMomentImage = IDL.Record({
  'id' : IDL.Text,
  'blob' : ExternalBlob,
  'name' : IDL.Text,
  'uploadTime' : Time,
});
export const SpecialMomentDTO = IDL.Record({
  'id' : IDL.Nat,
  'date' : Time,
  'name' : IDL.Text,
  'images' : IDL.Vec(SpecialMomentImage),
});
export const Video = IDL.Record({
  'id' : IDL.Text,
  'blob' : ExternalBlob,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'uploadTime' : Time,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const EventFilter = IDL.Record({
  'endDate' : IDL.Opt(Time),
  'searchText' : IDL.Opt(IDL.Text),
  'startDate' : IDL.Opt(Time),
});
export const PhotoFilter = IDL.Record({
  'endDate' : IDL.Opt(Time),
  'searchText' : IDL.Opt(IDL.Text),
  'startDate' : IDL.Opt(Time),
});
export const SpecialMomentFilter = IDL.Record({
  'endDate' : IDL.Opt(Time),
  'searchText' : IDL.Opt(IDL.Text),
  'startDate' : IDL.Opt(Time),
});
export const VideoFilter = IDL.Record({
  'endDate' : IDL.Opt(Time),
  'searchText' : IDL.Opt(IDL.Text),
  'startDate' : IDL.Opt(Time),
});
export const FooterContent = IDL.Record({
  'instagram' : IDL.Text,
  'facebook' : IDL.Text,
  'youtube' : IDL.Text,
  'contactDetails' : IDL.Text,
});
export const Visitor = IDL.Record({
  'principal' : IDL.Principal,
  'timestamp' : Time,
});
export const UpdateOrderRequest = IDL.Record({
  'customerName' : IDL.Opt(IDL.Text),
  'fulfillDate' : IDL.Opt(Time),
  'numberOfDvd' : IDL.Opt(IDL.Nat),
  'numberOfPrints' : IDL.Opt(IDL.Nat),
});
export const UpdateOrderStatusRequest = IDL.Record({ 'status' : OrderStatus });
export const EventImageUploadRequest = IDL.Record({
  'eventId' : IDL.Nat,
  'blob' : ExternalBlob,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const UploadResult = IDL.Record({
  'message' : IDL.Text,
  'success' : IDL.Bool,
});
export const PhotoVideoUploadRequest = IDL.Record({
  'blob' : ExternalBlob,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const MultiPhotoUploadRequest = IDL.Record({
  'photos' : IDL.Vec(PhotoVideoUploadRequest),
});
export const SpecialMomentImageUploadRequest = IDL.Record({
  'specialMomentId' : IDL.Nat,
  'blob' : ExternalBlob,
  'name' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createEvent' : IDL.Func([EventCreateRequest], [IDL.Nat], []),
  'createNewAuthenticatedUser' : IDL.Func([], [IDL.Bool], []),
  'createOrder' : IDL.Func([CreateOrderRequest], [IDL.Nat], []),
  'createSpecialMoment' : IDL.Func([SpecialMomentCreateRequest], [IDL.Nat], []),
  'deleteEvent' : IDL.Func([IDL.Nat], [], []),
  'deleteEventImage' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'deleteOrder' : IDL.Func([IDL.Nat], [], []),
  'deletePhoto' : IDL.Func([IDL.Text], [], []),
  'deleteSpecialMoment' : IDL.Func([IDL.Nat], [], []),
  'deleteSpecialMomentImage' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'deleteVideo' : IDL.Func([IDL.Text], [], []),
  'getAllEventsSorted' : IDL.Func(
      [SortedOrder],
      [IDL.Vec(EventDTO)],
      ['query'],
    ),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllOrdersSortedByDate' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllPhotosSorted' : IDL.Func([SortedOrder], [IDL.Vec(Photo)], ['query']),
  'getAllShortlistedImagesForUser' : IDL.Func(
      [IDL.Principal, IDL.Nat],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getAllShortlistsForAdmin' : IDL.Func(
      [],
      [IDL.Vec(UserShortlistDTO)],
      ['query'],
    ),
  'getAllSpecialMomentsSorted' : IDL.Func(
      [SortedOrder],
      [IDL.Vec(SpecialMomentDTO)],
      ['query'],
    ),
  'getAllVideosSorted' : IDL.Func([SortedOrder], [IDL.Vec(Video)], ['query']),
  'getAppVersion' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEvent' : IDL.Func([IDL.Nat], [EventDTO], ['query']),
  'getEventImages' : IDL.Func(
      [IDL.Nat, SortedOrder],
      [IDL.Vec(EventImage)],
      ['query'],
    ),
  'getFilteredEvents' : IDL.Func(
      [SortedOrder, EventFilter],
      [IDL.Vec(EventDTO)],
      ['query'],
    ),
  'getFilteredPhotos' : IDL.Func(
      [SortedOrder, PhotoFilter],
      [IDL.Vec(Photo)],
      ['query'],
    ),
  'getFilteredSpecialMoments' : IDL.Func(
      [SortedOrder, SpecialMomentFilter],
      [IDL.Vec(SpecialMomentDTO)],
      ['query'],
    ),
  'getFilteredVideos' : IDL.Func(
      [SortedOrder, VideoFilter],
      [IDL.Vec(Video)],
      ['query'],
    ),
  'getFooterContent' : IDL.Func([], [FooterContent], ['query']),
  'getLikedPhotos' : IDL.Func([IDL.Principal], [IDL.Vec(IDL.Text)], ['query']),
  'getOrder' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
  'getOrdersByStatus' : IDL.Func([OrderStatus], [IDL.Vec(Order)], ['query']),
  'getPasswordProtectedEvents' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
  'getPhotoLikeCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getShortlistCountForImage' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Nat],
      ['query'],
    ),
  'getShortlistedImagesForUser' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getSpecialMoment' : IDL.Func([IDL.Nat], [SpecialMomentDTO], ['query']),
  'getSpecialMomentsImages' : IDL.Func(
      [IDL.Nat, SortedOrder],
      [IDL.Vec(SpecialMomentImage)],
      ['query'],
    ),
  'getTotalLikeCountForUser' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserShortlistAcrossEvents' : IDL.Func(
      [],
      [IDL.Vec(UserShortlistDTO)],
      ['query'],
    ),
  'getVisitors' : IDL.Func(
      [IDL.Record({ 'limit' : IDL.Nat, 'start' : IDL.Nat })],
      [IDL.Vec(Visitor)],
      [],
    ),
  'hasUserLikedPhoto' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'hasUserLikedPhotoExplicit' : IDL.Func(
      [IDL.Principal, IDL.Text],
      [IDL.Bool],
      ['query'],
    ),
  'hasUserShortlistedImage' : IDL.Func(
      [IDL.Principal, IDL.Nat, IDL.Text],
      [IDL.Bool],
      ['query'],
    ),
  'hasUserShortlistedImageForCaller' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Bool],
      ['query'],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isEventPasswordProtected' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
  'recordVisitor' : IDL.Func([], [], []),
  'removeEventPassword' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setEventPassword' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'togglePhotoLike' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'toggleShortlist' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
  'updateEvent' : IDL.Func([IDL.Nat, EventCreateRequest], [], []),
  'updateFooterContent' : IDL.Func([FooterContent], [], []),
  'updateOrder' : IDL.Func([IDL.Nat, UpdateOrderRequest], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Nat, UpdateOrderStatusRequest], [], []),
  'uploadEventImage' : IDL.Func([EventImageUploadRequest], [UploadResult], []),
  'uploadMultiplePhotos' : IDL.Func(
      [MultiPhotoUploadRequest],
      [IDL.Vec(UploadResult)],
      [],
    ),
  'uploadPhoto' : IDL.Func([PhotoVideoUploadRequest], [UploadResult], []),
  'uploadSpecialMomentImage' : IDL.Func(
      [SpecialMomentImageUploadRequest],
      [UploadResult],
      [],
    ),
  'uploadVideo' : IDL.Func([PhotoVideoUploadRequest], [UploadResult], []),
  'validateEventPassword' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const EventCreateRequest = IDL.Record({
    'date' : Time,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const CreateOrderRequest = IDL.Record({
    'customerName' : IDL.Text,
    'orderDate' : Time,
    'fulfillDate' : Time,
    'numberOfDvd' : IDL.Nat,
    'numberOfPrints' : IDL.Nat,
  });
  const SpecialMomentCreateRequest = IDL.Record({
    'date' : Time,
    'name' : IDL.Text,
  });
  const SortedOrder = IDL.Variant({
    'newestFirst' : IDL.Null,
    'oldestFirst' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const EventImage = IDL.Record({
    'id' : IDL.Text,
    'blob' : ExternalBlob,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'uploadTime' : Time,
  });
  const EventDTO = IDL.Record({
    'id' : IDL.Nat,
    'date' : Time,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'passwordProtected' : IDL.Bool,
    'images' : IDL.Vec(EventImage),
  });
  const OrderStatus = IDL.Variant({
    'Cancelled' : IDL.Null,
    'Fulfilled' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'status' : OrderStatus,
    'orderDate' : Time,
    'fulfillDate' : Time,
    'numberOfDvd' : IDL.Nat,
    'numberOfPrints' : IDL.Nat,
  });
  const Photo = IDL.Record({
    'id' : IDL.Text,
    'likeCount' : IDL.Nat,
    'blob' : ExternalBlob,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'uploadTime' : Time,
  });
  const UserShortlistDTO = IDL.Record({
    'eventId' : IDL.Nat,
    'user' : IDL.Principal,
    'images' : IDL.Vec(IDL.Text),
  });
  const SpecialMomentImage = IDL.Record({
    'id' : IDL.Text,
    'blob' : ExternalBlob,
    'name' : IDL.Text,
    'uploadTime' : Time,
  });
  const SpecialMomentDTO = IDL.Record({
    'id' : IDL.Nat,
    'date' : Time,
    'name' : IDL.Text,
    'images' : IDL.Vec(SpecialMomentImage),
  });
  const Video = IDL.Record({
    'id' : IDL.Text,
    'blob' : ExternalBlob,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'uploadTime' : Time,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const EventFilter = IDL.Record({
    'endDate' : IDL.Opt(Time),
    'searchText' : IDL.Opt(IDL.Text),
    'startDate' : IDL.Opt(Time),
  });
  const PhotoFilter = IDL.Record({
    'endDate' : IDL.Opt(Time),
    'searchText' : IDL.Opt(IDL.Text),
    'startDate' : IDL.Opt(Time),
  });
  const SpecialMomentFilter = IDL.Record({
    'endDate' : IDL.Opt(Time),
    'searchText' : IDL.Opt(IDL.Text),
    'startDate' : IDL.Opt(Time),
  });
  const VideoFilter = IDL.Record({
    'endDate' : IDL.Opt(Time),
    'searchText' : IDL.Opt(IDL.Text),
    'startDate' : IDL.Opt(Time),
  });
  const FooterContent = IDL.Record({
    'instagram' : IDL.Text,
    'facebook' : IDL.Text,
    'youtube' : IDL.Text,
    'contactDetails' : IDL.Text,
  });
  const Visitor = IDL.Record({
    'principal' : IDL.Principal,
    'timestamp' : Time,
  });
  const UpdateOrderRequest = IDL.Record({
    'customerName' : IDL.Opt(IDL.Text),
    'fulfillDate' : IDL.Opt(Time),
    'numberOfDvd' : IDL.Opt(IDL.Nat),
    'numberOfPrints' : IDL.Opt(IDL.Nat),
  });
  const UpdateOrderStatusRequest = IDL.Record({ 'status' : OrderStatus });
  const EventImageUploadRequest = IDL.Record({
    'eventId' : IDL.Nat,
    'blob' : ExternalBlob,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const UploadResult = IDL.Record({
    'message' : IDL.Text,
    'success' : IDL.Bool,
  });
  const PhotoVideoUploadRequest = IDL.Record({
    'blob' : ExternalBlob,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const MultiPhotoUploadRequest = IDL.Record({
    'photos' : IDL.Vec(PhotoVideoUploadRequest),
  });
  const SpecialMomentImageUploadRequest = IDL.Record({
    'specialMomentId' : IDL.Nat,
    'blob' : ExternalBlob,
    'name' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createEvent' : IDL.Func([EventCreateRequest], [IDL.Nat], []),
    'createNewAuthenticatedUser' : IDL.Func([], [IDL.Bool], []),
    'createOrder' : IDL.Func([CreateOrderRequest], [IDL.Nat], []),
    'createSpecialMoment' : IDL.Func(
        [SpecialMomentCreateRequest],
        [IDL.Nat],
        [],
      ),
    'deleteEvent' : IDL.Func([IDL.Nat], [], []),
    'deleteEventImage' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'deleteOrder' : IDL.Func([IDL.Nat], [], []),
    'deletePhoto' : IDL.Func([IDL.Text], [], []),
    'deleteSpecialMoment' : IDL.Func([IDL.Nat], [], []),
    'deleteSpecialMomentImage' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'deleteVideo' : IDL.Func([IDL.Text], [], []),
    'getAllEventsSorted' : IDL.Func(
        [SortedOrder],
        [IDL.Vec(EventDTO)],
        ['query'],
      ),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllOrdersSortedByDate' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllPhotosSorted' : IDL.Func([SortedOrder], [IDL.Vec(Photo)], ['query']),
    'getAllShortlistedImagesForUser' : IDL.Func(
        [IDL.Principal, IDL.Nat],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getAllShortlistsForAdmin' : IDL.Func(
        [],
        [IDL.Vec(UserShortlistDTO)],
        ['query'],
      ),
    'getAllSpecialMomentsSorted' : IDL.Func(
        [SortedOrder],
        [IDL.Vec(SpecialMomentDTO)],
        ['query'],
      ),
    'getAllVideosSorted' : IDL.Func([SortedOrder], [IDL.Vec(Video)], ['query']),
    'getAppVersion' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEvent' : IDL.Func([IDL.Nat], [EventDTO], ['query']),
    'getEventImages' : IDL.Func(
        [IDL.Nat, SortedOrder],
        [IDL.Vec(EventImage)],
        ['query'],
      ),
    'getFilteredEvents' : IDL.Func(
        [SortedOrder, EventFilter],
        [IDL.Vec(EventDTO)],
        ['query'],
      ),
    'getFilteredPhotos' : IDL.Func(
        [SortedOrder, PhotoFilter],
        [IDL.Vec(Photo)],
        ['query'],
      ),
    'getFilteredSpecialMoments' : IDL.Func(
        [SortedOrder, SpecialMomentFilter],
        [IDL.Vec(SpecialMomentDTO)],
        ['query'],
      ),
    'getFilteredVideos' : IDL.Func(
        [SortedOrder, VideoFilter],
        [IDL.Vec(Video)],
        ['query'],
      ),
    'getFooterContent' : IDL.Func([], [FooterContent], ['query']),
    'getLikedPhotos' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getOrder' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
    'getOrdersByStatus' : IDL.Func([OrderStatus], [IDL.Vec(Order)], ['query']),
    'getPasswordProtectedEvents' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
    'getPhotoLikeCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getShortlistCountForImage' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Nat],
        ['query'],
      ),
    'getShortlistedImagesForUser' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getSpecialMoment' : IDL.Func([IDL.Nat], [SpecialMomentDTO], ['query']),
    'getSpecialMomentsImages' : IDL.Func(
        [IDL.Nat, SortedOrder],
        [IDL.Vec(SpecialMomentImage)],
        ['query'],
      ),
    'getTotalLikeCountForUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Nat],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserShortlistAcrossEvents' : IDL.Func(
        [],
        [IDL.Vec(UserShortlistDTO)],
        ['query'],
      ),
    'getVisitors' : IDL.Func(
        [IDL.Record({ 'limit' : IDL.Nat, 'start' : IDL.Nat })],
        [IDL.Vec(Visitor)],
        [],
      ),
    'hasUserLikedPhoto' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'hasUserLikedPhotoExplicit' : IDL.Func(
        [IDL.Principal, IDL.Text],
        [IDL.Bool],
        ['query'],
      ),
    'hasUserShortlistedImage' : IDL.Func(
        [IDL.Principal, IDL.Nat, IDL.Text],
        [IDL.Bool],
        ['query'],
      ),
    'hasUserShortlistedImageForCaller' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Bool],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isEventPasswordProtected' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
    'recordVisitor' : IDL.Func([], [], []),
    'removeEventPassword' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setEventPassword' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'togglePhotoLike' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'toggleShortlist' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
    'updateEvent' : IDL.Func([IDL.Nat, EventCreateRequest], [], []),
    'updateFooterContent' : IDL.Func([FooterContent], [], []),
    'updateOrder' : IDL.Func([IDL.Nat, UpdateOrderRequest], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Nat, UpdateOrderStatusRequest], [], []),
    'uploadEventImage' : IDL.Func(
        [EventImageUploadRequest],
        [UploadResult],
        [],
      ),
    'uploadMultiplePhotos' : IDL.Func(
        [MultiPhotoUploadRequest],
        [IDL.Vec(UploadResult)],
        [],
      ),
    'uploadPhoto' : IDL.Func([PhotoVideoUploadRequest], [UploadResult], []),
    'uploadSpecialMomentImage' : IDL.Func(
        [SpecialMomentImageUploadRequest],
        [UploadResult],
        [],
      ),
    'uploadVideo' : IDL.Func([PhotoVideoUploadRequest], [UploadResult], []),
    'validateEventPassword' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };