/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Video {
    id: string;
    blob: ExternalBlob;
    name: string;
    description: string;
    uploadTime: Time;
}
export interface PhotoVideoUploadRequest {
    blob: ExternalBlob;
    name: string;
    description: string;
}
export type Time = bigint;
export interface VideoFilter {
    endDate?: Time;
    searchText?: string;
    startDate?: Time;
}
export interface SpecialMomentFilter {
    endDate?: Time;
    searchText?: string;
    startDate?: Time;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface SpecialMomentCreateRequest {
    date: Time;
    name: string;
}
export interface PhotoFilter {
    endDate?: Time;
    searchText?: string;
    startDate?: Time;
}
export interface EventDTO {
    id: bigint;
    date: Time;
    name: string;
    description: string;
    passwordProtected: boolean;
    images: Array<EventImage>;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface SpecialMomentDTO {
    id: bigint;
    date: Time;
    name: string;
    images: Array<SpecialMomentImage>;
}
export interface UploadResult {
    message: string;
    success: boolean;
}
export interface Visitor {
    principal: Principal;
    timestamp: Time;
}
export interface SpecialMomentImage {
    id: string;
    blob: ExternalBlob;
    name: string;
    uploadTime: Time;
}
export interface MultiPhotoUploadRequest {
    photos: Array<PhotoVideoUploadRequest>;
}
export interface Photo {
    id: string;
    likeCount: bigint;
    blob: ExternalBlob;
    name: string;
    description: string;
    uploadTime: Time;
}
export interface EventImage {
    id: string;
    blob: ExternalBlob;
    name: string;
    description: string;
    uploadTime: Time;
}
export interface UserShortlistDTO {
    eventId: bigint;
    user: Principal;
    images: Array<string>;
}
export interface SpecialMomentImageUploadRequest {
    specialMomentId: bigint;
    blob: ExternalBlob;
    name: string;
}
export interface EventFilter {
    endDate?: Time;
    searchText?: string;
    startDate?: Time;
}
export interface EventCreateRequest {
    date: Time;
    name: string;
    description: string;
}
export interface EventImageUploadRequest {
    eventId: bigint;
    blob: ExternalBlob;
    name: string;
    description: string;
}
export interface FooterContent {
    instagram: string;
    facebook: string;
    youtube: string;
    contactDetails: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface UserProfile {
    name: string;
}
export enum SortedOrder {
    newestFirst = "newestFirst",
    oldestFirst = "oldestFirst"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createEvent(request: EventCreateRequest): Promise<bigint>;
    createNewAuthenticatedUser(): Promise<boolean>;
    createSpecialMoment(request: SpecialMomentCreateRequest): Promise<bigint>;
    deleteEvent(eventId: bigint): Promise<void>;
    deleteEventImage(eventId: bigint, imageId: string): Promise<void>;
    deletePhoto(id: string): Promise<void>;
    deleteSpecialMoment(specialMomentId: bigint): Promise<void>;
    deleteSpecialMomentImage(specialMomentId: bigint, imageId: string): Promise<void>;
    deleteVideo(id: string): Promise<void>;
    getAllEventsSorted(order: SortedOrder): Promise<Array<EventDTO>>;
    getAllPhotosSorted(order: SortedOrder): Promise<Array<Photo>>;
    getAllShortlistedImagesForUser(explicitUser: Principal, eventId: bigint): Promise<Array<string>>;
    getAllShortlistsForAdmin(): Promise<Array<UserShortlistDTO>>;
    getAllSpecialMomentsSorted(order: SortedOrder): Promise<Array<SpecialMomentDTO>>;
    getAllVideosSorted(order: SortedOrder): Promise<Array<Video>>;
    getAppVersion(): Promise<string>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getEvent(eventId: bigint): Promise<EventDTO>;
    getEventImages(eventId: bigint, order: SortedOrder): Promise<Array<EventImage>>;
    getFilteredEvents(order: SortedOrder, filter: EventFilter): Promise<Array<EventDTO>>;
    getFilteredPhotos(order: SortedOrder, filter: PhotoFilter): Promise<Array<Photo>>;
    getFilteredSpecialMoments(order: SortedOrder, filter: SpecialMomentFilter): Promise<Array<SpecialMomentDTO>>;
    getFilteredVideos(order: SortedOrder, filter: VideoFilter): Promise<Array<Video>>;
    getFooterContent(): Promise<FooterContent>;
    getLikedPhotos(user: Principal): Promise<Array<string>>;
    getPasswordProtectedEvents(): Promise<Array<bigint>>;
    getPhotoLikeCount(photoId: string): Promise<bigint>;
    getShortlistCountForImage(eventId: bigint, imageId: string): Promise<bigint>;
    getShortlistedImagesForUser(eventId: bigint): Promise<Array<string>>;
    getSpecialMoment(specialMomentId: bigint): Promise<SpecialMomentDTO>;
    getSpecialMomentsImages(specialMomentId: bigint, order: SortedOrder): Promise<Array<SpecialMomentImage>>;
    getTotalLikeCountForUser(user: Principal): Promise<bigint>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserShortlistAcrossEvents(): Promise<Array<UserShortlistDTO>>;
    getVisitors(pagination: {
        limit: bigint;
        start: bigint;
    }): Promise<Array<Visitor>>;
    hasUserLikedPhoto(photoId: string): Promise<boolean>;
    hasUserLikedPhotoExplicit(user: Principal, photoId: string): Promise<boolean>;
    hasUserShortlistedImage(explicitUser: Principal, eventId: bigint, imageId: string): Promise<boolean>;
    hasUserShortlistedImageForCaller(eventId: bigint, imageId: string): Promise<boolean>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    isEventPasswordProtected(eventId: bigint): Promise<boolean>;
    recordVisitor(): Promise<void>;
    removeEventPassword(eventId: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setEventPassword(eventId: bigint, password: string): Promise<void>;
    togglePhotoLike(photoId: string): Promise<boolean>;
    toggleShortlist(eventId: bigint, imageId: string): Promise<boolean>;
    updateEvent(eventId: bigint, request: EventCreateRequest): Promise<void>;
    updateFooterContent(content: FooterContent): Promise<void>;
    uploadEventImage(request: EventImageUploadRequest): Promise<UploadResult>;
    uploadMultiplePhotos(request: MultiPhotoUploadRequest): Promise<Array<UploadResult>>;
    uploadPhoto(request: PhotoVideoUploadRequest): Promise<UploadResult>;
    uploadSpecialMomentImage(request: SpecialMomentImageUploadRequest): Promise<UploadResult>;
    uploadVideo(request: PhotoVideoUploadRequest): Promise<UploadResult>;
    validateEventPassword(eventId: bigint, password: string): Promise<boolean>;
}
import type { EventDTO as _EventDTO, EventFilter as _EventFilter, EventImage as _EventImage, EventImageUploadRequest as _EventImageUploadRequest, ExternalBlob as _ExternalBlob, MultiPhotoUploadRequest as _MultiPhotoUploadRequest, Photo as _Photo, PhotoFilter as _PhotoFilter, PhotoVideoUploadRequest as _PhotoVideoUploadRequest, SortedOrder as _SortedOrder, SpecialMomentDTO as _SpecialMomentDTO, SpecialMomentFilter as _SpecialMomentFilter, SpecialMomentImage as _SpecialMomentImage, SpecialMomentImageUploadRequest as _SpecialMomentImageUploadRequest, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, Video as _Video, VideoFilter as _VideoFilter, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createEvent(arg0: EventCreateRequest): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEvent(arg0);
            return result;
        }
    }
    async createNewAuthenticatedUser(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.createNewAuthenticatedUser();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createNewAuthenticatedUser();
            return result;
        }
    }
    async createSpecialMoment(arg0: SpecialMomentCreateRequest): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createSpecialMoment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSpecialMoment(arg0);
            return result;
        }
    }
    async deleteEvent(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEvent(arg0);
            return result;
        }
    }
    async deleteEventImage(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEventImage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEventImage(arg0, arg1);
            return result;
        }
    }
    async deletePhoto(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePhoto(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePhoto(arg0);
            return result;
        }
    }
    async deleteSpecialMoment(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSpecialMoment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSpecialMoment(arg0);
            return result;
        }
    }
    async deleteSpecialMomentImage(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSpecialMomentImage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSpecialMomentImage(arg0, arg1);
            return result;
        }
    }
    async deleteVideo(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteVideo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteVideo(arg0);
            return result;
        }
    }
    async getAllEventsSorted(arg0: SortedOrder): Promise<Array<EventDTO>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEventsSorted(to_candid_SortedOrder_n10(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEventsSorted(to_candid_SortedOrder_n10(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPhotosSorted(arg0: SortedOrder): Promise<Array<Photo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPhotosSorted(to_candid_SortedOrder_n10(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPhotosSorted(to_candid_SortedOrder_n10(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllShortlistedImagesForUser(arg0: Principal, arg1: bigint): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllShortlistedImagesForUser(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllShortlistedImagesForUser(arg0, arg1);
            return result;
        }
    }
    async getAllShortlistsForAdmin(): Promise<Array<UserShortlistDTO>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllShortlistsForAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllShortlistsForAdmin();
            return result;
        }
    }
    async getAllSpecialMomentsSorted(arg0: SortedOrder): Promise<Array<SpecialMomentDTO>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSpecialMomentsSorted(to_candid_SortedOrder_n10(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSpecialMomentsSorted(to_candid_SortedOrder_n10(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllVideosSorted(arg0: SortedOrder): Promise<Array<Video>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllVideosSorted(to_candid_SortedOrder_n10(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllVideosSorted(to_candid_SortedOrder_n10(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAppVersion(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppVersion();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppVersion();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEvent(arg0: bigint): Promise<EventDTO> {
        if (this.processError) {
            try {
                const result = await this.actor.getEvent(arg0);
                return from_candid_EventDTO_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEvent(arg0);
            return from_candid_EventDTO_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEventImages(arg0: bigint, arg1: SortedOrder): Promise<Array<EventImage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEventImages(arg0, to_candid_SortedOrder_n10(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEventImages(arg0, to_candid_SortedOrder_n10(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFilteredEvents(arg0: SortedOrder, arg1: EventFilter): Promise<Array<EventDTO>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFilteredEvents(to_candid_SortedOrder_n10(this._uploadFile, this._downloadFile, arg0), to_candid_EventFilter_n33(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFilteredEvents(to_candid_SortedOrder_n10(this._uploadFile, this._downloadFile, arg0), to_candid_EventFilter_n33(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFilteredPhotos(arg0: SortedOrder, arg1: PhotoFilter): Promise<Array<Photo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFilteredPhotos(to_candid_SortedOrder_n10(this._uploadFile, this._downloadFile, arg0), to_candid_PhotoFilter_n35(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFilteredPhotos(to_candid_SortedOrder_n10(this._uploadFile, this._downloadFile, arg0), to_candid_PhotoFilter_n35(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFilteredSpecialMoments(arg0: SortedOrder, arg1: SpecialMomentFilter): Promise<Array<SpecialMomentDTO>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFilteredSpecialMoments(to_candid_SortedOrder_n10(this._uploadFile, this._downloadFile, arg0), to_candid_SpecialMomentFilter_n36(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFilteredSpecialMoments(to_candid_SortedOrder_n10(this._uploadFile, this._downloadFile, arg0), to_candid_SpecialMomentFilter_n36(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFilteredVideos(arg0: SortedOrder, arg1: VideoFilter): Promise<Array<Video>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFilteredVideos(to_candid_SortedOrder_n10(this._uploadFile, this._downloadFile, arg0), to_candid_VideoFilter_n37(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFilteredVideos(to_candid_SortedOrder_n10(this._uploadFile, this._downloadFile, arg0), to_candid_VideoFilter_n37(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFooterContent(): Promise<FooterContent> {
        if (this.processError) {
            try {
                const result = await this.actor.getFooterContent();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFooterContent();
            return result;
        }
    }
    async getLikedPhotos(arg0: Principal): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLikedPhotos(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLikedPhotos(arg0);
            return result;
        }
    }
    async getPasswordProtectedEvents(): Promise<Array<bigint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPasswordProtectedEvents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPasswordProtectedEvents();
            return result;
        }
    }
    async getPhotoLikeCount(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getPhotoLikeCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPhotoLikeCount(arg0);
            return result;
        }
    }
    async getShortlistCountForImage(arg0: bigint, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getShortlistCountForImage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getShortlistCountForImage(arg0, arg1);
            return result;
        }
    }
    async getShortlistedImagesForUser(arg0: bigint): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getShortlistedImagesForUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getShortlistedImagesForUser(arg0);
            return result;
        }
    }
    async getSpecialMoment(arg0: bigint): Promise<SpecialMomentDTO> {
        if (this.processError) {
            try {
                const result = await this.actor.getSpecialMoment(arg0);
                return from_candid_SpecialMomentDTO_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSpecialMoment(arg0);
            return from_candid_SpecialMomentDTO_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSpecialMomentsImages(arg0: bigint, arg1: SortedOrder): Promise<Array<SpecialMomentImage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSpecialMomentsImages(arg0, to_candid_SortedOrder_n10(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSpecialMomentsImages(arg0, to_candid_SortedOrder_n10(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTotalLikeCountForUser(arg0: Principal): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalLikeCountForUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalLikeCountForUser(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserShortlistAcrossEvents(): Promise<Array<UserShortlistDTO>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserShortlistAcrossEvents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserShortlistAcrossEvents();
            return result;
        }
    }
    async getVisitors(arg0: {
        limit: bigint;
        start: bigint;
    }): Promise<Array<Visitor>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVisitors(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVisitors(arg0);
            return result;
        }
    }
    async hasUserLikedPhoto(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasUserLikedPhoto(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasUserLikedPhoto(arg0);
            return result;
        }
    }
    async hasUserLikedPhotoExplicit(arg0: Principal, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasUserLikedPhotoExplicit(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasUserLikedPhotoExplicit(arg0, arg1);
            return result;
        }
    }
    async hasUserShortlistedImage(arg0: Principal, arg1: bigint, arg2: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasUserShortlistedImage(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasUserShortlistedImage(arg0, arg1, arg2);
            return result;
        }
    }
    async hasUserShortlistedImageForCaller(arg0: bigint, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasUserShortlistedImageForCaller(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasUserShortlistedImageForCaller(arg0, arg1);
            return result;
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isEventPasswordProtected(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isEventPasswordProtected(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isEventPasswordProtected(arg0);
            return result;
        }
    }
    async recordVisitor(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordVisitor();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordVisitor();
            return result;
        }
    }
    async removeEventPassword(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeEventPassword(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeEventPassword(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setEventPassword(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setEventPassword(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setEventPassword(arg0, arg1);
            return result;
        }
    }
    async togglePhotoLike(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.togglePhotoLike(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.togglePhotoLike(arg0);
            return result;
        }
    }
    async toggleShortlist(arg0: bigint, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleShortlist(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleShortlist(arg0, arg1);
            return result;
        }
    }
    async updateEvent(arg0: bigint, arg1: EventCreateRequest): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEvent(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEvent(arg0, arg1);
            return result;
        }
    }
    async updateFooterContent(arg0: FooterContent): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFooterContent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFooterContent(arg0);
            return result;
        }
    }
    async uploadEventImage(arg0: EventImageUploadRequest): Promise<UploadResult> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadEventImage(await to_candid_EventImageUploadRequest_n38(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadEventImage(await to_candid_EventImageUploadRequest_n38(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async uploadMultiplePhotos(arg0: MultiPhotoUploadRequest): Promise<Array<UploadResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadMultiplePhotos(await to_candid_MultiPhotoUploadRequest_n41(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadMultiplePhotos(await to_candid_MultiPhotoUploadRequest_n41(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async uploadPhoto(arg0: PhotoVideoUploadRequest): Promise<UploadResult> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadPhoto(await to_candid_PhotoVideoUploadRequest_n44(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadPhoto(await to_candid_PhotoVideoUploadRequest_n44(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async uploadSpecialMomentImage(arg0: SpecialMomentImageUploadRequest): Promise<UploadResult> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadSpecialMomentImage(await to_candid_SpecialMomentImageUploadRequest_n46(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadSpecialMomentImage(await to_candid_SpecialMomentImageUploadRequest_n46(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async uploadVideo(arg0: PhotoVideoUploadRequest): Promise<UploadResult> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadVideo(await to_candid_PhotoVideoUploadRequest_n44(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadVideo(await to_candid_PhotoVideoUploadRequest_n44(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async validateEventPassword(arg0: bigint, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.validateEventPassword(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateEventPassword(arg0, arg1);
            return result;
        }
    }
}
async function from_candid_EventDTO_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EventDTO): Promise<EventDTO> {
    return await from_candid_record_n14(_uploadFile, _downloadFile, value);
}
async function from_candid_EventImage_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EventImage): Promise<EventImage> {
    return await from_candid_record_n17(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_Photo_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Photo): Promise<Photo> {
    return await from_candid_record_n21(_uploadFile, _downloadFile, value);
}
async function from_candid_SpecialMomentDTO_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SpecialMomentDTO): Promise<SpecialMomentDTO> {
    return await from_candid_record_n24(_uploadFile, _downloadFile, value);
}
async function from_candid_SpecialMomentImage_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SpecialMomentImage): Promise<SpecialMomentImage> {
    return await from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
async function from_candid_Video_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Video): Promise<Video> {
    return await from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    date: _Time;
    name: string;
    description: string;
    passwordProtected: boolean;
    images: Array<_EventImage>;
}): Promise<{
    id: bigint;
    date: Time;
    name: string;
    description: string;
    passwordProtected: boolean;
    images: Array<EventImage>;
}> {
    return {
        id: value.id,
        date: value.date,
        name: value.name,
        description: value.description,
        passwordProtected: value.passwordProtected,
        images: await from_candid_vec_n15(_uploadFile, _downloadFile, value.images)
    };
}
async function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    blob: _ExternalBlob;
    name: string;
    description: string;
    uploadTime: _Time;
}): Promise<{
    id: string;
    blob: ExternalBlob;
    name: string;
    description: string;
    uploadTime: Time;
}> {
    return {
        id: value.id,
        blob: await from_candid_ExternalBlob_n18(_uploadFile, _downloadFile, value.blob),
        name: value.name,
        description: value.description,
        uploadTime: value.uploadTime
    };
}
async function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    likeCount: bigint;
    blob: _ExternalBlob;
    name: string;
    description: string;
    uploadTime: _Time;
}): Promise<{
    id: string;
    likeCount: bigint;
    blob: ExternalBlob;
    name: string;
    description: string;
    uploadTime: Time;
}> {
    return {
        id: value.id,
        likeCount: value.likeCount,
        blob: await from_candid_ExternalBlob_n18(_uploadFile, _downloadFile, value.blob),
        name: value.name,
        description: value.description,
        uploadTime: value.uploadTime
    };
}
async function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    date: _Time;
    name: string;
    images: Array<_SpecialMomentImage>;
}): Promise<{
    id: bigint;
    date: Time;
    name: string;
    images: Array<SpecialMomentImage>;
}> {
    return {
        id: value.id,
        date: value.date,
        name: value.name,
        images: await from_candid_vec_n25(_uploadFile, _downloadFile, value.images)
    };
}
async function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    blob: _ExternalBlob;
    name: string;
    uploadTime: _Time;
}): Promise<{
    id: string;
    blob: ExternalBlob;
    name: string;
    uploadTime: Time;
}> {
    return {
        id: value.id,
        blob: await from_candid_ExternalBlob_n18(_uploadFile, _downloadFile, value.blob),
        name: value.name,
        uploadTime: value.uploadTime
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_EventDTO>): Promise<Array<EventDTO>> {
    return await Promise.all(value.map(async (x)=>await from_candid_EventDTO_n13(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_EventImage>): Promise<Array<EventImage>> {
    return await Promise.all(value.map(async (x)=>await from_candid_EventImage_n16(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Photo>): Promise<Array<Photo>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Photo_n20(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SpecialMomentDTO>): Promise<Array<SpecialMomentDTO>> {
    return await Promise.all(value.map(async (x)=>await from_candid_SpecialMomentDTO_n23(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SpecialMomentImage>): Promise<Array<SpecialMomentImage>> {
    return await Promise.all(value.map(async (x)=>await from_candid_SpecialMomentImage_n26(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Video>): Promise<Array<Video>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Video_n29(_uploadFile, _downloadFile, x)));
}
function to_candid_EventFilter_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EventFilter): _EventFilter {
    return to_candid_record_n34(_uploadFile, _downloadFile, value);
}
async function to_candid_EventImageUploadRequest_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EventImageUploadRequest): Promise<_EventImageUploadRequest> {
    return await to_candid_record_n39(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_MultiPhotoUploadRequest_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MultiPhotoUploadRequest): Promise<_MultiPhotoUploadRequest> {
    return await to_candid_record_n42(_uploadFile, _downloadFile, value);
}
function to_candid_PhotoFilter_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PhotoFilter): _PhotoFilter {
    return to_candid_record_n34(_uploadFile, _downloadFile, value);
}
async function to_candid_PhotoVideoUploadRequest_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PhotoVideoUploadRequest): Promise<_PhotoVideoUploadRequest> {
    return await to_candid_record_n45(_uploadFile, _downloadFile, value);
}
function to_candid_SortedOrder_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SortedOrder): _SortedOrder {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_SpecialMomentFilter_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SpecialMomentFilter): _SpecialMomentFilter {
    return to_candid_record_n34(_uploadFile, _downloadFile, value);
}
async function to_candid_SpecialMomentImageUploadRequest_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SpecialMomentImageUploadRequest): Promise<_SpecialMomentImageUploadRequest> {
    return await to_candid_record_n47(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_VideoFilter_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VideoFilter): _VideoFilter {
    return to_candid_record_n34(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    endDate?: Time;
    searchText?: string;
    startDate?: Time;
}): {
    endDate: [] | [_Time];
    searchText: [] | [string];
    startDate: [] | [_Time];
} {
    return {
        endDate: value.endDate ? candid_some(value.endDate) : candid_none(),
        searchText: value.searchText ? candid_some(value.searchText) : candid_none(),
        startDate: value.startDate ? candid_some(value.startDate) : candid_none()
    };
}
async function to_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    eventId: bigint;
    blob: ExternalBlob;
    name: string;
    description: string;
}): Promise<{
    eventId: bigint;
    blob: _ExternalBlob;
    name: string;
    description: string;
}> {
    return {
        eventId: value.eventId,
        blob: await to_candid_ExternalBlob_n40(_uploadFile, _downloadFile, value.blob),
        name: value.name,
        description: value.description
    };
}
async function to_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    photos: Array<PhotoVideoUploadRequest>;
}): Promise<{
    photos: Array<_PhotoVideoUploadRequest>;
}> {
    return {
        photos: await to_candid_vec_n43(_uploadFile, _downloadFile, value.photos)
    };
}
async function to_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    blob: ExternalBlob;
    name: string;
    description: string;
}): Promise<{
    blob: _ExternalBlob;
    name: string;
    description: string;
}> {
    return {
        blob: await to_candid_ExternalBlob_n40(_uploadFile, _downloadFile, value.blob),
        name: value.name,
        description: value.description
    };
}
async function to_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    specialMomentId: bigint;
    blob: ExternalBlob;
    name: string;
}): Promise<{
    specialMomentId: bigint;
    blob: _ExternalBlob;
    name: string;
}> {
    return {
        specialMomentId: value.specialMomentId,
        blob: await to_candid_ExternalBlob_n40(_uploadFile, _downloadFile, value.blob),
        name: value.name
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SortedOrder): {
    newestFirst: null;
} | {
    oldestFirst: null;
} {
    return value == SortedOrder.newestFirst ? {
        newestFirst: null
    } : value == SortedOrder.oldestFirst ? {
        oldestFirst: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
async function to_candid_vec_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<PhotoVideoUploadRequest>): Promise<Array<_PhotoVideoUploadRequest>> {
    return await Promise.all(value.map(async (x)=>await to_candid_PhotoVideoUploadRequest_n44(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
